# Generated by Django 5.2.4 on 2025-07-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('salary_range', models.CharField(blank=True, max_length=50, null=True)),
                ('hiring_timeline', models.CharField(help_text="e.g., 'August 2025', 'Batch 2026'", max_length=100)),
                ('drive_date', models.DateField(help_text='Primary date for ordering drives.')),
                ('location', models.CharField(max_length=100)),
                ('interview_process_description', models.TextField()),
            ],
            options={
                'ordering': ['drive_date'],
            },
        ),
    ]
