# Generated by Django 5.2.4 on 2025-07-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('Video', 'Video'), ('Article', 'Article'), ('Course', 'Course'), ('Problem Set', 'Problem Set')], max_length=50)),
                ('associated_topics', models.ManyToManyField(related_name='resources', to='core.learningtopic')),
            ],
        ),
        migrations.AddField(
            model_name='learningtopic',
            name='related_skills',
            field=models.ManyToManyField(related_name='topics', to='core.skill'),
        ),
    ]
