# Generated by Django 5.2.4 on 2025-07-24 17:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_discussiontopic_discussionpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreparationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(help_text='Simple user identification for hackathon', max_length=100)),
                ('plan_name', models.CharField(help_text='User-defined name for the plan', max_length=255)),
                ('academic_details', models.TextField()),
                ('input_type', models.CharField(choices=[('role', 'Target Role'), ('job_description', 'Job Description')], max_length=20)),
                ('preferred_role', models.CharField(blank=True, max_length=200, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('plan_data', models.JSONField(help_text='Complete plan data returned from AI')),
                ('total_topics', models.IntegerField(default=0)),
                ('completed_topics', models.IntegerField(default=0)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-last_accessed', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(help_text='Skill/section name', max_length=255)),
                ('topic_name', models.CharField(help_text='Specific topic name', max_length=255)),
                ('topic_description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_hours', models.FloatField(blank=True, null=True)),
                ('actual_hours_spent', models.FloatField(default=0.0)),
                ('user_notes', models.TextField(blank=True, help_text="User's personal notes on this topic")),
                ('difficulty_rating', models.IntegerField(blank=True, choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Medium'), (4, 'Hard'), (5, 'Very Hard')], help_text="User's difficulty rating for this topic", null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to='core.userpreparationplan')),
            ],
            options={
                'ordering': ['section_name', 'topic_name'],
                'unique_together': {('plan', 'section_name', 'topic_name')},
            },
        ),
    ]
