# Generated by Django 5.2.4 on 2025-07-24 20:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_discussiontopic_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon identifier', max_length=50)),
                ('color', models.CharField(default='#667eea', help_text='Hex color code for category', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Forum Category',
                'verbose_name_plural': 'Forum Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='discussiontopic',
            name='content',
            field=models.TextField(blank=True, help_text='Optional initial post content'),
        ),
        migrations.AddField(
            model_name='discussiontopic',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Prevent new posts'),
        ),
        migrations.AddField(
            model_name='discussiontopic',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pin topic to top of category'),
        ),
        migrations.AddField(
            model_name='discussiontopic',
            name='view_count',
            field=models.IntegerField(default=0, help_text='Number of times topic was viewed'),
        ),
        migrations.AddField(
            model_name='discussiontopic',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Forum category this topic belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core.forumcategory'),
        ),
    ]
