# Generated by Django 5.2.4 on 2025-07-24 21:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_forumcategory_discussiontopic_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('session_type', models.CharField(choices=[('voice', 'Voice'), ('text', 'Text')], default='voice', max_length=20)),
                ('total_questions', models.IntegerField()),
                ('questions_answered', models.IntegerField(default=0)),
                ('average_score', models.FloatField(blank=True, null=True)),
                ('performance_level', models.CharField(blank=True, max_length=50)),
                ('overall_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('difficulty_level', models.CharField(default='medium', max_length=20)),
                ('user_answer', models.TextField(blank=True)),
                ('answer_type', models.CharField(choices=[('voice', 'Voice'), ('text', 'Text')], default='voice', max_length=10)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('improvements', models.JSONField(blank=True, default=list)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('overall_comment', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='core.interviewsession')),
            ],
            options={
                'ordering': ['question_number'],
                'unique_together': {('session', 'question_number')},
            },
        ),
    ]
